# Generated by Django 6.0.7 on 2026-09-17 14:37

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(default=movie.models.get_default_array),
        ),
    ]
